/*
 html2canvas v0.33 <http://html2canvas.hertzen.com>
  Copyright (c) 2011 Niklas von Hertzen. All rights reserved.
  http://www.twitter.com/niklasvh

  Released under MIT License
*/
(function(p,w,u){function C(c){k.logging&&(p.console&&p.console.log)&&p.console.log(c)}function T(c,g){var f=[];return{storage:f,width:c,height:g,fillRect:function(){f.push({type:"function",name:"fillRect",arguments:arguments})},drawImage:function(){f.push({type:"function",name:"drawImage",arguments:arguments})},fillText:function(){f.push({type:"function",name:"fillText",arguments:arguments})},setVariable:function(a,d){f.push({type:"variable",name:a,arguments:d})}}}var k={},J;k.Util={};k.Util.backgroundImage=
function(c){if(/data:image\/.*;base64,/i.test(c)||/^(-webkit|-moz|linear-gradient|-o-)/.test(c))return c;'url("'===c.toLowerCase().substr(0,5)?(c=c.substr(5),c=c.substr(0,c.length-2)):(c=c.substr(4),c=c.substr(0,c.length-1));return c};k.Util.Bounds=function(c){var g={};if(c.getBoundingClientRect)return c=c.getBoundingClientRect(),g.top=c.top,g.bottom=c.bottom||c.top+c.height,g.left=c.left,g.width=c.width||c.right-c.left,g.height=c.height||c.bottom-c.top,g};k.Util.getCSS=function(c,g){function f(a,
b){var g=c.runtimeStyle&&c.runtimeStyle[a],f,o=c.style;if(!/^-?[0-9]+\.?[0-9]*(?:px)?$/i.test(b)&&/^-?\d/.test(b)&&(f=o.left,g&&(c.runtimeStyle.left=c.currentStyle.left),o.left="fontSize"===a?"1em":b||0,b=o.pixelLeft+"px",o.left=f,g))c.runtimeStyle.left=g;return!/^(thin|medium|thick)$/i.test(b)?Math.round(parseFloat(b))+"px":b}var a;if(p.getComputedStyle)a=w.defaultView.getComputedStyle(c,null)[g],"backgroundPosition"===g&&(a=(a.split(",")[0]||"0 0").split(" "),a[0]=-1===a[0].indexOf("%")?f(g+"X",
a[0]):a[0],a[1]=a[1]===u?a[0]:a[1],a[1]=-1===a[1].indexOf("%")?f(g+"Y",a[1]):a[1]);else if(c.currentStyle)if("backgroundPosition"===g)a=[f(g+"X",c.currentStyle[g+"X"]),f(g+"Y",c.currentStyle[g+"Y"])];else if(a=f(g,c.currentStyle[g]),/^(border)/i.test(g)&&/^(medium|thin|thick)$/i.test(a))switch(a){case "thin":a="1px";break;case "medium":a="0px";break;case "thick":a="5px"}return a};k.Util.BackgroundPosition=function(c,g,f){var c=k.Util.getCSS(c,"backgroundPosition"),a,d;1===c.length&&(a=c,c=[],c[0]=
a,c[1]=a);-1!==c[0].toString().indexOf("%")?(d=parseFloat(c[0])/100,a=g.width*d-f.width*d):a=parseInt(c[0],10);-1!==c[1].toString().indexOf("%")?(d=parseFloat(c[1])/100,g=g.height*d-f.height*d):g=parseInt(c[1],10);return{top:g,left:a}};k.Util.Extend=function(c,g){for(var f in c)c.hasOwnProperty(f)&&(g[f]=c[f]);return g};k.Util.Children=function(c){var g;try{g=$(c).contents()}catch(f){C("html2canvas.Util.Children failed with exception: "+f.message),g=[]}return g};(function(){k.Generate={};var c=[/^(-webkit-linear-gradient)\(([a-z\s]+)([\w\d\.\s,%\(\)]+)\)$/,
/^(-o-linear-gradient)\(([a-z\s]+)([\w\d\.\s,%\(\)]+)\)$/,/^(-webkit-gradient)\((linear|radial),\s((?:\d{1,3}%?)\s(?:\d{1,3}%?),\s(?:\d{1,3}%?)\s(?:\d{1,3}%?))([\w\d\.\s,%\(\)-]+)\)$/,/^(-moz-linear-gradient)\(((?:\d{1,3}%?)\s(?:\d{1,3}%?))([\w\d\.\s,%\(\)]+)\)$/,/^(-webkit-radial-gradient)\(((?:\d{1,3}%?)\s(?:\d{1,3}%?)),\s(\w+)\s([a-z-]+)([\w\d\.\s,%\(\)]+)\)$/,/^(-moz-radial-gradient)\(((?:\d{1,3}%?)\s(?:\d{1,3}%?)),\s(\w+)\s?([a-z-]*)([\w\d\.\s,%\(\)]+)\)$/,/^(-o-radial-gradient)\(((?:\d{1,3}%?)\s(?:\d{1,3}%?)),\s(\w+)\s([a-z-]+)([\w\d\.\s,%\(\)]+)\)$/];
k.Generate.parseGradient=function(g,f){var a,d,b=c.length,h,i,o,e;for(d=0;d<b&&!(h=g.match(c[d]));d+=1);if(h)switch(h[1]){case "-webkit-linear-gradient":case "-o-linear-gradient":a={type:"linear",x0:null,y0:null,x1:null,y1:null,colorStops:[]};if(b=h[2].match(/\w+/g)){i=b.length;for(d=0;d<i;d+=1)switch(b[d]){case "top":a.y0=0;a.y1=f.height;break;case "right":a.x0=f.width;a.x1=0;break;case "bottom":a.y0=f.height;a.y1=0;break;case "left":a.x0=0,a.x1=f.width}}null===a.x0&&null===a.x1&&(a.x0=a.x1=f.width/
2);null===a.y0&&null===a.y1&&(a.y0=a.y1=f.height/2);if(b=h[3].match(/((?:rgb|rgba)\(\d{1,3},\s\d{1,3},\s\d{1,3}(?:,\s[0-9\.]+)?\)(?:\s\d{1,3}(?:%|px))?)+/g)){i=b.length;o=1/Math.max(i-1,1);for(d=0;d<i;d+=1)e=b[d].match(/((?:rgb|rgba)\(\d{1,3},\s\d{1,3},\s\d{1,3}(?:,\s[0-9\.]+)?\))\s*(\d{1,3})?(%|px)?/),e[2]?(h=parseFloat(e[2]),h="%"===e[3]?h/100:h/f.width):h=d*o,a.colorStops.push({color:e[1],stop:h})}break;case "-webkit-gradient":a={type:"radial"===h[2]?"circle":h[2],x0:0,y0:0,x1:0,y1:0,colorStops:[]};
if(b=h[3].match(/(\d{1,3})%?\s(\d{1,3})%?,\s(\d{1,3})%?\s(\d{1,3})%?/))a.x0=b[1]*f.width/100,a.y0=b[2]*f.height/100,a.x1=b[3]*f.width/100,a.y1=b[4]*f.height/100;if(b=h[4].match(/((?:from|to|color-stop)\((?:[0-9\.]+,\s)?(?:rgb|rgba)\(\d{1,3},\s\d{1,3},\s\d{1,3}(?:,\s[0-9\.]+)?\)\))+/g)){i=b.length;for(d=0;d<i;d+=1)e=b[d].match(/(from|to|color-stop)\(([0-9\.]+)?(?:,\s)?((?:rgb|rgba)\(\d{1,3},\s\d{1,3},\s\d{1,3}(?:,\s[0-9\.]+)?\))\)/),h=parseFloat(e[2]),"from"===e[1]&&(h=0),"to"===e[1]&&(h=1),a.colorStops.push({color:e[3],
stop:h})}break;case "-moz-linear-gradient":a={type:"linear",x0:0,y0:0,x1:0,y1:0,colorStops:[]};if(b=h[2].match(/(\d{1,3})%?\s(\d{1,3})%?/))a.x0=b[1]*f.width/100,a.y0=b[2]*f.height/100,a.x1=f.width-a.x0,a.y1=f.height-a.y0;if(b=h[3].match(/((?:rgb|rgba)\(\d{1,3},\s\d{1,3},\s\d{1,3}(?:,\s[0-9\.]+)?\)(?:\s\d{1,3}%)?)+/g)){i=b.length;o=1/Math.max(i-1,1);for(d=0;d<i;d+=1)e=b[d].match(/((?:rgb|rgba)\(\d{1,3},\s\d{1,3},\s\d{1,3}(?:,\s[0-9\.]+)?\))\s*(\d{1,3})?(%)?/),e[2]?(h=parseFloat(e[2]),e[3]&&(h/=100)):
h=d*o,a.colorStops.push({color:e[1],stop:h})}break;case "-webkit-radial-gradient":case "-moz-radial-gradient":case "-o-radial-gradient":a={type:"circle",x0:0,y0:0,x1:f.width,y1:f.height,cx:0,cy:0,rx:0,ry:0,colorStops:[]};if(b=h[2].match(/(\d{1,3})%?\s(\d{1,3})%?/))a.cx=b[1]*f.width/100,a.cy=b[2]*f.height/100;b=h[3].match(/\w+/);e=h[4].match(/[a-z-]*/);if(b&&e)switch(e[0]){case "farthest-corner":case "cover":case "":d=Math.sqrt(Math.pow(a.cx,2)+Math.pow(a.cy,2));b=Math.sqrt(Math.pow(a.cx,2)+Math.pow(a.y1-
a.cy,2));i=Math.sqrt(Math.pow(a.x1-a.cx,2)+Math.pow(a.y1-a.cy,2));e=Math.sqrt(Math.pow(a.x1-a.cx,2)+Math.pow(a.cy,2));a.rx=a.ry=Math.max(d,b,i,e);break;case "closest-corner":d=Math.sqrt(Math.pow(a.cx,2)+Math.pow(a.cy,2));b=Math.sqrt(Math.pow(a.cx,2)+Math.pow(a.y1-a.cy,2));i=Math.sqrt(Math.pow(a.x1-a.cx,2)+Math.pow(a.y1-a.cy,2));e=Math.sqrt(Math.pow(a.x1-a.cx,2)+Math.pow(a.cy,2));a.rx=a.ry=Math.min(d,b,i,e);break;case "farthest-side":"circle"===b[0]?a.rx=a.ry=Math.max(a.cx,a.cy,a.x1-a.cx,a.y1-a.cy):
(a.type=b[0],a.rx=Math.max(a.cx,a.x1-a.cx),a.ry=Math.max(a.cy,a.y1-a.cy));break;case "closest-side":case "contain":"circle"===b[0]?a.rx=a.ry=Math.min(a.cx,a.cy,a.x1-a.cx,a.y1-a.cy):(a.type=b[0],a.rx=Math.min(a.cx,a.x1-a.cx),a.ry=Math.min(a.cy,a.y1-a.cy))}if(b=h[5].match(/((?:rgb|rgba)\(\d{1,3},\s\d{1,3},\s\d{1,3}(?:,\s[0-9\.]+)?\)(?:\s\d{1,3}(?:%|px))?)+/g)){i=b.length;o=1/Math.max(i-1,1);for(d=0;d<i;d+=1)e=b[d].match(/((?:rgb|rgba)\(\d{1,3},\s\d{1,3},\s\d{1,3}(?:,\s[0-9\.]+)?\))\s*(\d{1,3})?(%|px)?/),
e[2]?(h=parseFloat(e[2]),h="%"===e[3]?h/100:h/f.width):h=d*o,a.colorStops.push({color:e[1],stop:h})}}return a};k.Generate.Gradient=function(c,f){var a=w.createElement("canvas"),d=a.getContext("2d"),b,h,i,o,e;a.width=f.width;a.height=f.height;b=k.Generate.parseGradient(c,f);e=new Image;if(b)if("linear"===b.type){h=d.createLinearGradient(b.x0,b.y0,b.x1,b.y1);i=0;for(o=b.colorStops.length;i<o;i+=1)try{h.addColorStop(b.colorStops[i].stop,b.colorStops[i].color)}catch(p){C(["failed to add color stop: ",
p,"; tried to add: ",b.colorStops[i],"; stop: ",i,"; in: ",c])}d.fillStyle=h;d.fillRect(0,0,f.width,f.height);e.src=a.toDataURL()}else if("circle"===b.type){h=d.createRadialGradient(b.cx,b.cy,0,b.cx,b.cy,b.rx);i=0;for(o=b.colorStops.length;i<o;i+=1)try{h.addColorStop(b.colorStops[i].stop,b.colorStops[i].color)}catch(u){C(["failed to add color stop: ",u,"; tried to add: ",b.colorStops[i],"; stop: ",i,"; in: ",c])}d.fillStyle=h;d.fillRect(0,0,f.width,f.height);e.src=a.toDataURL()}else if("ellipse"===
b.type){var n=w.createElement("canvas"),q=n.getContext("2d");h=Math.max(b.rx,b.ry);var M=2*h,F;n.width=n.height=M;h=q.createRadialGradient(b.rx,b.ry,0,b.rx,b.ry,h);i=0;for(o=b.colorStops.length;i<o;i+=1)try{h.addColorStop(b.colorStops[i].stop,b.colorStops[i].color)}catch(z){C(["failed to add color stop: ",z,"; tried to add: ",b.colorStops[i],"; stop: ",i,"; in: ",c])}q.fillStyle=h;q.fillRect(0,0,M,M);d.fillStyle=b.colorStops[i-1].color;d.fillRect(0,0,a.width,a.height);F=new Image;F.onload=function(){d.drawImage(F,
b.cx-b.rx,b.cy-b.ry,2*b.rx,2*b.ry);e.src=a.toDataURL()};F.src=n.toDataURL()}return e};k.Generate.ListAlpha=function(c){var f="",a;do a=c%26,f=String.fromCharCode(a+64)+f,c/=26;while(26<26*c);return f};k.Generate.ListRoman=function(c){var f="M CM D CD C XC L XL X IX V IV I".split(" "),a=[1E3,900,500,400,100,90,50,40,10,9,5,4,1],d="",b,h=f.length;if(0>=c||4E3<=c)return c;for(b=0;b<h;b+=1)for(;c>=a[b];)c-=a[b],d+=f[b];return d}})();k.Parse=function(c,g){var f,a;function d(){return{width:Math.max(Math.max(r.body.scrollWidth,
r.documentElement.scrollWidth),Math.max(r.body.offsetWidth,r.documentElement.offsetWidth),Math.max(r.body.clientWidth,r.documentElement.clientWidth)),height:Math.max(Math.max(r.body.scrollHeight,r.documentElement.scrollHeight),Math.max(r.body.offsetHeight,r.documentElement.offsetHeight),Math.max(r.body.clientHeight,r.documentElement.clientHeight))}}function b(a,b){var c=parseInt(y(a,b),10);return isNaN(c)?0:c}function h(a,b,c,d,f,g){"transparent"!==g&&(a.setVariable("fillStyle",g),a.fillRect(b,c,
d,f))}function i(a,b){switch(b){case "lowercase":return a.toLowerCase();case "capitalize":return a.replace(/(^|\s|:|-|\(|\))([a-z])/g,function(a,b,U){if(0<a.length)return b+U.toUpperCase()});case "uppercase":return a.toUpperCase();default:return a}}function o(a){return a.replace(/^\s*/g,"").replace(/\s*$/g,"")}function e(a,b,c){var c=c.ctx,d=y(a,"fontFamily"),K=y(a,"fontSize"),z=y(a,"color"),B=y(a,"textDecoration"),e=y(a,"textAlign"),s=y(a,"letterSpacing"),H,m,n=y(a,"fontWeight"),q=y(a,"fontStyle"),
p=y(a,"fontVariant"),A=0,j;b.nodeValue=i(b.nodeValue,y(a,"textTransform"));if(0<o(b.nodeValue).length){if("none"!==B)if(v[d+"-"+K]!==u)m=v[d+"-"+K];else{m=r.createElement("div");a=r.createElement("img");j=r.createElement("span");var x;m.style.visibility="hidden";m.style.fontFamily=d;m.style.fontSize=K;m.style.margin=0;m.style.padding=0;l.appendChild(m);a.src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACwAAAAAAQABAAACAkQBADs=";a.width=1;a.height=1;a.style.margin=0;a.style.padding=0;a.style.verticalAlign=
"baseline";j.style.fontFamily=d;j.style.fontSize=K;j.style.margin=0;j.style.padding=0;j.appendChild(r.createTextNode("Hidden Text"));m.appendChild(j);m.appendChild(a);x=a.offsetTop-j.offsetTop+1;m.removeChild(j);m.appendChild(r.createTextNode("Hidden Text"));m.style.lineHeight="normal";a.style.verticalAlign="super";a={baseline:x,lineWidth:1,middle:a.offsetTop-m.offsetTop+1};v[d+"-"+K]=a;l.removeChild(m);m=a}e=e.replace(["-webkit-auto"],["auto"]);e=!1===g.letterRendering&&/^(left|right|justify|auto)$/.test(e)&&
/^(normal|none)$/.test(s)?b.nodeValue.split(/(\b| )/):b.nodeValue.split("");switch(parseInt(n,10)){case 401:n="bold";break;case 400:n="normal"}c.setVariable("fillStyle",z);c.setVariable("font",q+" "+p+" "+n+" "+K+" "+d);c.setVariable("textAlign","left");K=b;n=0;for(d=e.length;n<d;n+=1){q=null;if(f){if("none"!==B||0!==o(e[n]).length)q=e[n],r.createRange?(H=r.createRange(),H.setStart(b,A),H.setEnd(b,A+q.length)):H=l.createTextRange(),H=H.getBoundingClientRect()?H.getBoundingClientRect():{}}else{if("string"!==
typeof K.nodeValue)continue;p=K.splitText(e[n].length);s=K.parentNode;a=r.createElement("wrapper");j=K.cloneNode(!0);a.appendChild(K.cloneNode(!0));s.replaceChild(a,K);H=k.Util.Bounds(a);q=K.nodeValue;K=p;s.replaceChild(j,a)}null!==q&&(p=H.left,s=H.bottom,a=c,0<o(q).length&&a.fillText(q,p,s));switch(B){case "underline":h(c,H.left,Math.round(H.top+m.baseline+m.lineWidth),H.width,1,z);break;case "overline":h(c,H.left,H.top,H.width,1,z);break;case "line-through":h(c,H.left,Math.ceil(H.top+m.middle+m.lineWidth),
H.width,1,z)}A+=e[n].length}}}function O(a){return(a=c[a])&&!0===a.succeeded?a.img:!1}function R(a,b){var c=Math.max(a.left,b.left),d=Math.max(a.top,b.top),f=Math.min(a.left+a.width,b.left+b.width),g=Math.min(a.top+a.height,b.top+b.height);return{left:c,top:d,width:f-c,height:g-d}}function n(a,b,c){var d=r.createElement("valuewrap"),f="lineHeight textAlign fontFamily color fontSize paddingLeft paddingTop width height border borderLeftWidth borderTopWidth".split(" "),g,h,i;g=0;for(h=f.length;g<h;g+=
1){i=f[g];try{d.style[i]=y(a,i)}catch(z){C("html2canvas: Parse: Exception caught in renderFormValue: "+z.message)}}d.style.borderColor="black";d.style.borderStyle="solid";d.style.display="block";d.style.position="absolute";if(/^(submit|reset|button|text|password)$/.test(a.type)||"SELECT"===a.nodeName)d.style.lineHeight=y(a,"height");d.style.top=b.top+"px";d.style.left=b.left+"px";b=r.createTextNode("SELECT"===a.nodeName?a.options[a.selectedIndex].text:a.value);d.appendChild(b);l.appendChild(d);e(a,
b,c);l.removeChild(d)}function q(a,b,c,d,g,f,h,i){var e=0,z=0;0<h-c&&(e=h-c);0<i-d&&(z=i-d);a.drawImage(b,e,z,g-e,f-z,c+e,d+z,g-e,f-z)}function M(a,b,c,d,g,f,h){var h=Math.min(b.height,h),i,e;c.left-=Math.ceil(c.left/b.width)*b.width;for(e=d+c.left;e<f+d;)i=Math.floor(e+b.width)>f+d?f+d-e:b.width,q(a,b,e,g+c.top,i,h,d,g),e=Math.floor(e+b.width)}function F(a,c){var f,i,e=k.Util.Bounds(a),z=e.left,B=e.top,v=e.width,s=e.height,l,m=y(a,"backgroundColor"),p=y(a,"position"),u,G=y(a,"opacity"),A;c?J={}:
(J=d(),c={opacity:1});var j=y(a,"zIndex");(u=c.zIndex)?"auto"!==j&&(j={zindex:j,children:[]},u.children.push(j),u=j):u=j={zindex:0,children:[]};A={ctx:T(J.width||v,J.height||s),zIndex:u,opacity:G*c.opacity,cssPosition:p};c.clip&&(A.clip=k.Util.Extend({},c.clip));!0===g.useOverflow&&(!0===/(hidden|scroll|auto)/.test(y(a,"overflow"))&&!1===/(BODY)/i.test(a.nodeName))&&(A.clip=A.clip?R(A.clip,e):e);p=u.children.push(A);G=u.children[p-1].ctx;G.setVariable("globalAlpha",A.opacity);var x=e.left,t=e.top,
D=e.width,I=e.height,w,E,F,L,j=[];w=["Top","Right","Bottom","Left"];for(E=0;4>E;E+=1)j.push({width:b(a,"border"+w[E]+"Width"),color:y(a,"border"+w[E]+"Color")});for(w=0;4>w;w+=1)if(E=j[w],0<E.width){F=x;L=t;f=D;i=I-j[2].width;switch(w){case 0:i=j[0].width;break;case 1:F=x+D-j[1].width;f=j[1].width;break;case 2:L=L+I-j[2].width;i=j[2].width;break;case 3:f=j[3].width}0<f&&0<i&&h(G,F,L,f,i,E.color)}A.borders=j;S.test(a.nodeName)&&"transparent"!==g.iframeDefault&&(m="default"===g.iframeDefault?"#efefef":
g.iframeDefault);v={left:z+j[3].width,top:B+j[0].width,width:v-(j[1].width+j[3].width),height:s-(j[0].width+j[2].width)};A.clip&&(v=R(v,A.clip));if(0<v.height&&0<v.width&&(h(G,v.left,v.top,v.width,v.height,m),x=v,t=y(a,"backgroundImage"),D=y(a,"backgroundRepeat").split(",")[0],!/data:image\/.*;base64,/i.test(t)&&!/^(-webkit|-moz|linear-gradient|-o-)/.test(t)&&(t=t.split(",")[0]),"undefined"!==typeof t&&!1===/^(1|none)$/.test(t)))if(t=k.Util.backgroundImage(t),m=O(t),s=k.Util.BackgroundPosition(a,
x,m),m)switch(D){case "repeat-x":M(G,m,s,x.left,x.top,x.width,x.height);break;case "repeat-y":t=x.left;D=x.top;I=x.height;w=Math.min(m.width,x.width);s.top-=Math.ceil(s.top/m.height)*m.height;for(E=D+s.top;E<I+D;)x=Math.floor(E+m.height)>I+D?I+D-E:m.height,q(G,m,t+s.left,E,w,x,t,D),E=Math.floor(E+m.height);break;case "no-repeat":t=x.width-s.left;E=x.height-s.top;D=s.left;I=s.top;w=s.left+x.left;s=s.top+x.top;0>D?(D=Math.abs(D),w+=D,t=Math.min(x.width,m.width-D)):(t=Math.min(t,m.width),D=0);0>I?(I=
Math.abs(I),s+=I,E=Math.min(x.height,m.height-I)):(E=Math.min(E,m.height),I=0);0<E&&0<t&&G.drawImage(m,D,I,t,E,w,s,t,E);break;default:s.top-=Math.ceil(s.top/m.height)*m.height;for(t=x.top+s.top;t<x.height+x.top;)D=Math.min(m.height,x.height+x.top-t),D=Math.floor(t+m.height)>D+t?D+t-t:m.height,t<x.top?(I=x.top-t,t=x.top):I=0,M(G,m,s,x.left,t,x.width,D),0<I&&(s.top+=I),t=Math.floor(t+m.height)-I}else C("html2canvas: Error loading background:"+t);switch(a.nodeName){case "IMG":A=a.getAttribute("src");
(l=O(A))?(A=b(a,"paddingLeft"),m=b(a,"paddingTop"),v=b(a,"paddingRight"),s=b(a,"paddingBottom"),G.drawImage(l,0,0,l.width,l.height,z+A+j[3].width,B+m+j[0].width,e.width-(j[1].width+j[3].width+A+v),e.height-(j[0].width+j[2].width+m+s))):C("html2canvas: Error loading <img>:"+A);break;case "INPUT":/^(text|url|email|submit|button|reset)$/.test(a.type)&&0<a.value.length&&n(a,e,A);break;case "TEXTAREA":0<a.value.length&&n(a,e,A);break;case "SELECT":0<a.options.length&&n(a,e,A);break;case "LI":e=v;z=y(a,
"listStylePosition");G=y(a,"listStyleType");B=y(a,"fontWeight");if(/^(decimal|decimal-leading-zero|upper-alpha|upper-latin|upper-roman|lower-alpha|lower-greek|lower-latin|lower-roman)$/i.test(G)){j=$(a).index()+1;switch(G){case "decimal":l=j;break;case "decimal-leading-zero":l=1===j.toString().length?"0"+j.toString():j.toString();break;case "upper-roman":l=k.Generate.ListRoman(j);break;case "lower-roman":l=k.Generate.ListRoman(j).toLowerCase();break;case "lower-alpha":l=k.Generate.ListAlpha(j).toLowerCase();
break;case "upper-alpha":l=k.Generate.ListAlpha(j)}A=l+=". ";G=r.createElement("boundelement");G.style.display="inline";j=a.style.listStyleType;a.style.listStyleType="none";G.appendChild(r.createTextNode(A));a.insertBefore(G,a.firstChild);A=k.Util.Bounds(G);a.removeChild(G);a.style.listStyleType=j;switch(B){case 401:B="bold";break;case 400:B="normal"}P.setVariable("fillStyle",y(a,"color"));P.setVariable("font",y(a,"fontVariant")+" "+B+" "+y(a,"fontStyle")+" "+y(a,"fontSize")+" "+y(a,"fontFamily"));
"inside"===z&&(P.setVariable("textAlign","left"),e=e.left,z=A.bottom,B=P,0<o(l).length&&B.fillText(l,e,z))}break;case "CANVAS":A=b(a,"paddingLeft"),m=b(a,"paddingTop"),v=b(a,"paddingRight"),s=b(a,"paddingBottom"),G.drawImage(a,0,0,a.width,a.height,z+A+j[3].width,B+m+j[0].width,e.width-(j[1].width+j[3].width+A+v),e.height-(j[0].width+j[2].width+m+s))}return u.children[p-1]}function z(a,b){if("none"!==y(a,"display")&&"hidden"!==y(a,"visibility")&&(b=F(a,b)||b,P=b.ctx,!S.test(a.nodeName))){var c=k.Util.Children(a),
d,f,g;d=0;for(g=c.length;d<g;d+=1)f=c[d],1===f.nodeType?z(f,b):3===f.nodeType&&e(a,f,b)}}p.scroll(0,0);f=!1;a=g.svgRendering&&function(){var a=new Image,b=w.createElement("canvas"),c=b.getContext===u?!1:b.getContext("2d");if(!1===c)return!1;b.width=b.height=10;a.src="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' width='10' height='10'><foreignObject width='10' height='10'><div xmlns='http://www.w3.org/1999/xhtml' style='width:10;height:10;'>sup</div></foreignObject></svg>";try{c.drawImage(a,
0,0),b.toDataURL()}catch(d){return!1}C("html2canvas: Parse: SVG powered rendering available");return!0}();var B=g.elements===u?w.body:g.elements[0],v={},r=B.ownerDocument,S=RegExp("("+g.ignoreElements+")"),l=r.body,L,N,Q,P,J,c=c||{};r.createRange&&(L=r.createRange(),L.getBoundingClientRect&&(N=r.createElement("boundtest"),N.style.height="123px",N.style.display="block",l.appendChild(N),L.selectNode(N),L=L.getBoundingClientRect(),L=L.height,123===L&&(f=!0),l.removeChild(N)));var y=k.Util.getCSS;Q=F(B,
null);a&&function(a){function b(a){var a=k.Util.Children(a),c=a.length,d,f,g,i,h;for(h=0;h<c;h=h+1){i=a[h];if(i.nodeType===3)e=e+i.nodeValue.replace(/\</g,"&lt;").replace(/\>/g,"&gt;");else if(i.nodeType===1&&!/^(script|meta|title)$/.test(i.nodeName.toLowerCase())){e=e+("<"+i.nodeName.toLowerCase());if(i.hasAttributes()){d=i.attributes;g=d.length;for(f=0;f<g;f=f+1)e=e+(" "+d[f].name+'="'+d[f].value+'"')}e=e+">";b(i);e=e+("</"+i.nodeName.toLowerCase()+">")}}}var c=new Image,f=d(),e="";b(a);c.src=["data:image/svg+xml,",
"<svg xmlns='http://www.w3.org/2000/svg' version='1.1' width='"+f.width+"' height='"+f.height+"'>","<foreignObject width='"+f.width+"' height='"+f.height+"'>","<html xmlns='http://www.w3.org/1999/xhtml' style='margin:0;'>",e.replace(/\#/g,"%23"),"</html></foreignObject></svg>"].join("");c.onload=function(){Q.svgRender=c}}(w.documentElement);a=0;B=B.children;for(N=B.length;a<N;a+=1)z(B[a],Q);Q.backgroundColor=y(w.documentElement,"backgroundColor");return Q};k.Preload=function(c){function g(){C("html2canvas: start: images: "+
b.numLoaded+" / "+b.numTotal+" (failed: "+b.numFailed+")");!b.firstRun&&b.numLoaded>=b.numTotal&&(C("Finished loading images: # "+b.numTotal+" (failed: "+b.numFailed+")"),"function"===typeof c.complete&&c.complete(b))}function f(a,f,i){var h,o=c.proxy,l;q.href=a;a=q.href;h="html2canvas_"+e++;i.callbackname=h;o=-1<o.indexOf("?")?o+"&":o+"?";o+="url="+encodeURIComponent(a)+"&callback="+h;l=O.createElement("script");p[h]=function(a){"error:"===a.substring(0,6)?(i.succeeded=!1,b.numLoaded++,b.numFailed++,
g()):(d(f,i),f.src=a);p[h]=u;try{delete p[h]}catch(c){}l.parentNode.removeChild(l);l=null;delete i.script;delete i.callbackname};l.setAttribute("type","text/javascript");l.setAttribute("src",o);i.script=l;p.document.body.appendChild(l)}function a(c){var d=k.Util.Children(c),f,e=d.length,h,o=!1;for(f=0;f<e;f+=1)a(d[f]);try{o=c.nodeType}catch(n){o=!1,C("html2canvas: failed to access some element's nodeType - Exception: "+n.message)}if(1===o||o===u){try{h=k.Util.getCSS(c,"backgroundImage")}catch(q){C("html2canvas: failed to get background-image - Exception: "+
q.message)}h&&("1"!==h&&"none"!==h)&&(/^(-webkit|-o|-moz|-ms|linear)-/.test(h)?(c=k.Generate.Gradient(h,k.Util.Bounds(c)),c!==u&&(b[h]={img:c,succeeded:!0},b.numTotal++,b.numLoaded++,g())):(h=k.Util.backgroundImage(h.match(/data:image\/.*;base64,/i)?h:h.split(",")[0]),i.loadImage(h)))}}function d(a,d){a.onload=function(){d.timer!==u&&p.clearTimeout(d.timer);b.numLoaded++;d.succeeded=!0;a.onerror=a.onload=null;g()};a.onerror=function(){if("anonymous"===a.crossOrigin&&(p.clearTimeout(d.timer),c.proxy)){var e=
a.src;a=new Image;d.img=a;a.src=e;f(a.src,a,d);return}b.numLoaded++;b.numFailed++;d.succeeded=!1;a.onerror=a.onload=null;g()}}var b={numLoaded:0,numFailed:0,numTotal:0,cleanupDone:!1},h,i,o,e=0;o=c.elements[0]||w.body;var O=o.ownerDocument,J=O.images,n=J.length,q=O.createElement("a"),M=function(a){return a.crossOrigin!==u}(new Image),F;q.href=p.location.href;h=q.protocol+q.host;i={loadImage:function(a){var e,i;a&&b[a]===u&&(e=new Image,a.match(/data:image\/.*;base64,/i)?(e.src=a.replace(/url\(['"]{0,}|['"]{0,}\)$/ig,
""),i=b[a]={img:e},b.numTotal++,d(e,i)):(q.href=a.replace("filesystem:",""),q.href=q.href,q.protocol+q.host===h||!0===c.allowTaint?(i=b[a]={img:e},b.numTotal++,d(e,i),e.src=a):M&&!c.allowTaint&&c.useCORS?(e.crossOrigin="anonymous",i=b[a]={img:e},b.numTotal++,d(e,i),e.src=a,e.customComplete=function(){if(this.img.complete)this.img.onerror();else this.timer=p.setTimeout(this.img.customComplete,100)}.bind(i),e.customComplete()):c.proxy&&(i=b[a]={img:e},b.numTotal++,f(a,e,i))))},cleanupDOM:function(a){var d,
e;if(!b.cleanupDone){a&&"string"===typeof a?C("html2canvas: Cleanup because: "+a):C("html2canvas: Cleanup after timeout: "+c.timeout+" ms.");for(e in b)if(b.hasOwnProperty(e)&&(d=b[e],"object"===typeof d&&d.callbackname&&d.succeeded===u)){p[d.callbackname]=u;try{delete p[d.callbackname]}catch(f){}d.script&&d.script.parentNode&&(d.script.setAttribute("src","about:blank"),d.script.parentNode.removeChild(d.script));b.numLoaded++;b.numFailed++;C("html2canvas: Cleaned up failed img: '"+e+"' Steps: "+b.numLoaded+
" / "+b.numTotal)}p.stop!==u?p.stop():w.execCommand!==u&&w.execCommand("Stop",!1);w.close!==u&&w.close();b.cleanupDone=!0;a&&"string"===typeof a||g()}},renderingDone:function(){F&&p.clearTimeout(F)}};0<c.timeout&&(F=p.setTimeout(i.cleanupDOM,c.timeout));C("html2canvas: Preload starts: finding background-images");b.firstRun=!0;a(o);C("html2canvas: Preload: Finding images");for(o=0;o<n;o+=1)i.loadImage(J[o].getAttribute("src"));b.firstRun=!1;C("html2canvas: Preload: Done.");b.numTotal===b.numLoaded&&
g();return i};k.Renderer=function(c,g){function f(d){var b=[],c=[],d=d.children,i,g,e,k;i=0;for(e=d.length;i<e;i+=1)g=d[i],g.children&&0<g.children.length?(b.push(g),c.push(g.zindex)):a.push(g);c.sort(function(a,b){return a-b});d=0;for(i=c.length;d<i;d+=1){g=c[d];e=0;for(k=b.length;e<=k;e+=1)if(b[e].zindex===g){g=b.splice(e,1);f(g[0]);break}}}var a=[];f(c.zIndex);if("function"!==typeof g._renderer._create)throw Error("Invalid renderer defined");return g._renderer._create(c,g,w,a,k)};J=function(c,
g){var f,a,d={logging:!1,elements:c,proxy:"https://html2canvas.appspot.com/",timeout:0,useCORS:!1,allowTaint:!1,svgRendering:!1,iframeDefault:"default",ignoreElements:"IFRAME|OBJECT|PARAM",useOverflow:!0,letterRendering:!1,flashcanvas:u,width:null,height:null,taintTest:!0,renderer:"Canvas"},d=k.Util.Extend(g,d);if("string"===typeof d.renderer&&k.Renderer[d.renderer]!==u)d._renderer=k.Renderer[d.renderer](d);else if("function"===typeof d.renderer)d._renderer=d.renderer(d);else throw"Unknown renderer";
k.logging=d.logging;d.complete=function(b){if(!("function"===typeof d.onpreloaded&&!1===d.onpreloaded(b))&&(f=k.Parse(b,d),!("function"===typeof d.onparsed&&!1===d.onparsed(f))&&(a=k.Renderer(f,d),"function"===typeof d.onrendered)))d.onrendered(a)};p.setTimeout(function(){k.Preload(d)},0);return{render:function(a,c){return k.Renderer(a,k.Util.Extend(c,d))},parse:function(a,c){return k.Parse(a,k.Util.Extend(c,d))},preload:function(a){return k.Preload(k.Util.Extend(a,d))},log:C}};J.log=C;J.Renderer=
{Canvas:u};k.Renderer.Canvas=function(c){var c=c||{},g=c.canvas||w.createElement("canvas"),f=!1,a=!1,d=!1,b;if(g.getContext)C("html2canvas: Renderer: using canvas renderer"),d=!0;else if(c.flashcanvas!==u){f=!0;C("html2canvas: Renderer: canvas not available, using flashcanvas");var h=w.createElement("script");h.src=c.flashcanvas;h.onload=function(a,b){var c;if(a.onload===u)a.onreadystatechange!==u?(c=function(){"loaded"!==a.readyState&&"complete"!==a.readyState?p.setTimeout(c,250):b()},p.setTimeout(c,
250)):C("html2canvas: Renderer: Can't track when flashcanvas is loaded");else return b}(h,function(){"undefined"!==typeof p.FlashCanvas&&(C("html2canvas: Renderer: Flashcanvas initialized"),p.FlashCanvas.initElement(g),d=!0,!1!==a&&b._create.apply(null,a))});w.body.appendChild(h)}return b={_create:function(b,c,e,h,k){if(!d)return a=arguments,g;var n=g.getContext("2d"),q,p,F,z,B,v,r=w.createElement("canvas");B=r.getContext!==u;var J,l,r=B?r.getContext("2d"):{};v=[];g.width=g.style.width=!f?c.width||
b.ctx.width:Math.min(2880,c.width||b.ctx.width);g.height=g.style.height=!f?c.height||b.ctx.height:Math.min(2880,c.height||b.ctx.height);q=n.fillStyle;n.fillStyle=b.backgroundColor;n.fillRect(0,0,g.width,g.height);n.fillStyle=q;if(c.svgRendering&&b.svgRender!==u)n.drawImage(b.svgRender,0,0);else{p=0;for(F=h.length;p<F;p+=1){q=h.splice(0,1)[0];q.canvasPosition=q.canvasPosition||{};n.textBaseline="bottom";q.clip&&(n.save(),n.beginPath(),n.rect(q.clip.left,q.clip.top,q.clip.width,q.clip.height),n.clip());
if(q.ctx.storage){z=0;for(J=q.ctx.storage.length;z<J;z+=1)switch(l=q.ctx.storage[z],l.type){case "variable":n[l.name]=l.arguments;break;case "function":if("fillRect"===l.name)(!f||2880>l.arguments[0]+l.arguments[2]&&2880>l.arguments[1]+l.arguments[3])&&n.fillRect.apply(n,l.arguments);else if("fillText"===l.name)(!f||2880>l.arguments[1]&&2880>l.arguments[2])&&n.fillText.apply(n,l.arguments);else if("drawImage"===l.name&&0<l.arguments[8]&&l.arguments[7]){if(B&&c.taintTest&&-1===v.indexOf(l.arguments[0].src)){r.drawImage(l.arguments[0],
0,0);try{r.getImageData(0,0,1,1)}catch(L){r=e.createElement("canvas");r=r.getContext("2d");continue}v.push(l.arguments[0].src)}n.drawImage.apply(n,l.arguments)}}}q.clip&&n.restore()}}C("html2canvas: Renderer: Canvas renderer done - returning canvas obj");F=c.elements.length;return 1===F&&"object"===typeof c.elements[0]&&"BODY"!==c.elements[0].nodeName&&!1===f?(v=k.Util.Bounds(c.elements[0]),B=e.createElement("canvas"),B.width=v.width,B.height=v.height,n=B.getContext("2d"),n.drawImage(g,v.left,v.top,
v.width,v.height,0,0,v.width,v.height),g=null,B):g}}};p.html2canvas=J})(window,document);
